### ISSUE TITLE
Texture extraction 

### ISSUE THREAD

**Issue by ansj11** [l1346792580123/PatchShading#6]
I see that your rendered image from mesh is very realistic. So I want to know how to get the texture, can you give me your texture extraction and rendering code

**Comment by l1346792580123** [comment]
You can check the [rendering code](https://github.com/l1346792580123/FastHuman/blob/bab1bb9662cb6bc060398c21d195bb04c605edd7/sfs_optim.py#L100-L120) in [sfs_optim.py](https://github.com/l1346792580123/FastHuman/blob/main/sfs_optim.py). The texture is stored as per vertex color in the saved pt file. You can construct the colored obj file like
```
mesh = trimesh.Trimesh(np_verts, np_faces, vertcex_color=albedo.squeeze().cpu().numpy())
```

or you can check this [issue](https://github.com/l1346792580123/diff/issues/1) to construct the textured obj.

**Comment by ansj11** [comment]
thank you for your quick reply! I used your rendering code but got a textured mesh with some abnormal colors. Is it normal?

https://github.com/l1346792580123/FastHuman/assets/24786133/74ec6bcb-9b7b-4a9f-9347-b237218380ba

**Comment by l1346792580123** [comment]
This is because this part does not appear in the images, so the albedo of this part is not optimized. You can load all the NHR images by changing the resolution in [get_nhr_data](https://github.com/l1346792580123/FastHuman/blob/bab1bb9662cb6bc060398c21d195bb04c605edd7/get_data.py#L55C43-L55C46) and employ [sfs_optim](https://github.com/l1346792580123/FastHuman/blob/main/sfs_optim.py) to get the final albedo.

**Comment by Moxx2047** [comment]
> 感谢您的快速回复！我使用了您的渲染代码，但得到了一个带有一些异常颜色的纹理网格。正常吗？
> 
>  2024-05-27.17.21.50.mov

请问您的纹理方法是怎么进行的我一直没有得到纹理
